version: '3.7'
services:
  notebook:
    build: notebook
    image: notebook
    ports:
      - "8888:8888"
    volumes: 
      - ./moneyaggvoc:/moneyaggvoc
  jekyll:
    build: jekyll
    image: jekyll
    volumes: 
      - ./jekyll:/srv/jekyll
      - ./moneyaggvoc:/srv/jekyll/moneyaggvoc
