source "https://rubygems.org"

gem "jekyll", "~> 4.0.0"
gem "jekyll-watch", "~> 2.2.1"

gem "minima", "~> 2.5.1"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
  gem "jekyll-rdf", '~> 3.1.0'
end
